'use client'
import { ResponsiveContainer,LineChart,Line,BarChart,Bar,CartesianGrid,XAxis,YAxis,Tooltip,Legend,AreaChart,Area } from 'recharts'
import { forecast,historical } from '@/data/mock-weather'
const axis={fontSize:11,fill:'var(--muted-foreground)'}
export function TemperatureChart(){return <ChartBox><ResponsiveContainer><LineChart data={forecast}><CartesianGrid strokeDasharray="3 3" stroke="var(--border)"/><XAxis dataKey="date" tick={axis}/><YAxis tick={axis}/><Tooltip/><Legend/><Line type="monotone" dataKey="maxTemp" name="Maximum °C" stroke="var(--chart-1)" strokeWidth={3}/><Line type="monotone" dataKey="minTemp" name="Minimum °C" stroke="var(--chart-2)" strokeWidth={3}/></LineChart></ResponsiveContainer></ChartBox>}
export function RainChart(){return <ChartBox><ResponsiveContainer><BarChart data={forecast}><CartesianGrid strokeDasharray="3 3" stroke="var(--border)"/><XAxis dataKey="date" tick={axis}/><YAxis tick={axis}/><Tooltip/><Bar dataKey="rainfall" name="Rainfall (mm)" fill="var(--chart-2)" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></ChartBox>}
export function HumidityChart(){return <ChartBox><ResponsiveContainer><AreaChart data={forecast}><defs><linearGradient id="hum" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="var(--chart-3)" stopOpacity={.3}/><stop offset="95%" stopColor="var(--chart-3)" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="var(--border)"/><XAxis dataKey="date" tick={axis}/><YAxis tick={axis}/><Tooltip/><Area type="monotone" dataKey="humidity" name="Humidity (%)" stroke="var(--chart-3)" fill="url(#hum)" strokeWidth={3}/></AreaChart></ResponsiveContainer></ChartBox>}
export function HistoricalChart({rain=false}:{rain?:boolean}){return <ChartBox><ResponsiveContainer>{rain?<BarChart data={historical}><CartesianGrid strokeDasharray="3 3" stroke="var(--border)"/><XAxis dataKey="month" tick={axis}/><YAxis tick={axis}/><Tooltip/><Bar dataKey="rainfall" fill="var(--chart-2)" radius={[3,3,0,0]}/></BarChart>:<LineChart data={historical}><CartesianGrid strokeDasharray="3 3" stroke="var(--border)"/><XAxis dataKey="month" tick={axis}/><YAxis tick={axis}/><Tooltip/><Legend/><Line dataKey="actual" name="Observed" stroke="var(--chart-1)" strokeWidth={3}/><Line dataKey="predicted" name="AI Downscaled" stroke="var(--chart-2)" strokeDasharray="5 4" strokeWidth={3}/></LineChart>}</ResponsiveContainer></ChartBox>}
function ChartBox({children}:{children:React.ReactNode}){return <div className="h-72 w-full pt-4">{children}</div>}
