/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiDownscalingRouteImport } from './routes/ai-downscaling'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CropAdvisoryRouteImport } from './routes/crop-advisory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as HistoricalRouteImport } from './routes/historical'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as WeatherMapRouteImport } from './routes/weather-map'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDownscalingRoute = AiDownscalingRouteImport.update({
  id: '/ai-downscaling',
  path: '/ai-downscaling',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CropAdvisoryRoute = CropAdvisoryRouteImport.update({
  id: '/crop-advisory',
  path: '/crop-advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricalRoute = HistoricalRouteImport.update({
  id: '/historical',
  path: '/historical',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherMapRoute = WeatherMapRouteImport.update({
  id: '/weather-map',
  path: '/weather-map',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-downscaling': typeof AiDownscalingRoute
  '/alerts': typeof AlertsRoute
  '/crop-advisory': typeof CropAdvisoryRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/historical': typeof HistoricalRoute
  '/methodology': typeof MethodologyRoute
  '/weather-map': typeof WeatherMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-downscaling': typeof AiDownscalingRoute
  '/alerts': typeof AlertsRoute
  '/crop-advisory': typeof CropAdvisoryRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/historical': typeof HistoricalRoute
  '/methodology': typeof MethodologyRoute
  '/weather-map': typeof WeatherMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-downscaling': typeof AiDownscalingRoute
  '/alerts': typeof AlertsRoute
  '/crop-advisory': typeof CropAdvisoryRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/historical': typeof HistoricalRoute
  '/methodology': typeof MethodologyRoute
  '/weather-map': typeof WeatherMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-downscaling'
    | '/alerts'
    | '/crop-advisory'
    | '/dashboard'
    | '/forecast'
    | '/historical'
    | '/methodology'
    | '/weather-map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-downscaling'
    | '/alerts'
    | '/crop-advisory'
    | '/dashboard'
    | '/forecast'
    | '/historical'
    | '/methodology'
    | '/weather-map'
  id:
    | '__root__'
    | '/'
    | '/ai-downscaling'
    | '/alerts'
    | '/crop-advisory'
    | '/dashboard'
    | '/forecast'
    | '/historical'
    | '/methodology'
    | '/weather-map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDownscalingRoute: typeof AiDownscalingRoute
  AlertsRoute: typeof AlertsRoute
  CropAdvisoryRoute: typeof CropAdvisoryRoute
  DashboardRoute: typeof DashboardRoute
  ForecastRoute: typeof ForecastRoute
  HistoricalRoute: typeof HistoricalRoute
  MethodologyRoute: typeof MethodologyRoute
  WeatherMapRoute: typeof WeatherMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-downscaling': {
      id: '/ai-downscaling'
      path: '/ai-downscaling'
      fullPath: '/ai-downscaling'
      preLoaderRoute: typeof AiDownscalingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-advisory': {
      id: '/crop-advisory'
      path: '/crop-advisory'
      fullPath: '/crop-advisory'
      preLoaderRoute: typeof CropAdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historical': {
      id: '/historical'
      path: '/historical'
      fullPath: '/historical'
      preLoaderRoute: typeof HistoricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather-map': {
      id: '/weather-map'
      path: '/weather-map'
      fullPath: '/weather-map'
      preLoaderRoute: typeof WeatherMapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDownscalingRoute: AiDownscalingRoute,
  AlertsRoute: AlertsRoute,
  CropAdvisoryRoute: CropAdvisoryRoute,
  DashboardRoute: DashboardRoute,
  ForecastRoute: ForecastRoute,
  HistoricalRoute: HistoricalRoute,
  MethodologyRoute: MethodologyRoute,
  WeatherMapRoute: WeatherMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
